export const DATA_ADD_VARIABLE = Symbol('data-add-variable')
export const DATA_LOAD = Symbol('data-load')
export const DATA_REMOVE_VARIABLE = Symbol('data-remove-variable')
export const DATA_SET_MODEL = Symbol('data-set-model')
export const DATA_TOGGLE_LAYER = Symbol('data-toggle-layer')
export const DATA_TOGGLE_VARIABLE_TYPE = Symbol('data-toggle-variable-type')
export const DATA_UPDATE_THRESHOLD = Symbol('data-update-threshold')
